name: Car Makes SuggestMode
version: 1.0.0
description: SuggestMode for list of auto manufacturers
url: https://github.com/notasausage/statamic-suggestmode-cars
developer: Patrick Haney
developer_url: http://patrickhaney.com
